### ISSUE TITLE
Modify enableOnSite per Retention Science engineering

### ISSUE THREAD

**Issue by beckysteele** [astronomer-integrations/analytics.js-integration-retention-science#6]
Line 9 of Index.js shows that `_enableOnSite` is a Boolean (checkbox in our UI) that defaults to false.  https://github.com/astronomer-integrations/analytics.js-integration-retention-science/blob/master/lib/index.js#L9

There's a function on Line 89 that does `this._push(['_enableOnSite'])` when the checkbox is checked (enabled `true`).
https://github.com/astronomer-integrations/analytics.js-integration-retention-science/blob/master/lib/index.js#L89

According to Retention Science's Jonathan Fox, Senior Enterprise Solutions Architect, we should be doing `this._push(['_enableOnSite'])` 100% of the time; it should not be optional for the user, because without this the Retention Science tags do not fire.  See attached docs for reference on their tags and how enableOnsite should be deployed in each one, 100% of the time.

Please let me know when this is done (tag me here), and I'll update the docs (which are going to be published today instructing the user to check the enableOnSite box all the time).  Thanks so much!
[JavaScript-General-Setup.html.zip](https://github.com/astronomer-integrations/analytics.js-integration-retention-science/files/1197708/JavaScript-General-Setup.html.zip)

**Comment by thisisamurray** [comment]
I can remove that flag and do a clean-up migration to remove that setting from existing configs, but will need help updating the integration itself to always use it  (@byerc ) .

**Comment by byerc** [comment]
Let's knock this out whenever you get the chance @thisisamurray

**Comment by thisisamurray** [comment]
@byerc sounds good to me! Can update existing configs tomorrow if that works for you

**Comment by thisisamurray** [comment]
@byerc Circling back, there is only 3 configs on prod that have it. I'll be able to migrate them within minutes once I get the all clear from you.

**Comment by thisisamurray** [comment]
@byerc Removing myself from this ticket. Once you update the integration, add me back and I'll run the migration.

**Comment by byerc** [comment]
@thisisamurray got it. Sorry, I'm not sure how I missed your comment last week. I'll get this updated and reassign.

**Comment by byerc** [comment]
i made the code changes and opened a [pull request] (https://github.com/astronomer-integrations/analytics.js-integration-retention-science/pull/7) (a review is required to merge) and tagged you @thisisamurray

**Comment by thisisamurray** [comment]
Haha, I am not auth'd to merge. @schnie You mind merging the PR Collen references?

**Comment by thisisamurray** [comment]
`enableOnSite` has been removed from the forms. @byerc Let me know when I can update the integration records, once analytics.js is pointed to the new version.

**Comment by thisisamurray** [comment]
@byerc Circling back, let me know when I'm cleared to proceed :smile:

**Comment by byerc** [comment]
@thisisamurray i'm getting the latest build of the analytics.js-builder deployed to prod right now and then you should be good to go.

**Comment by byerc** [comment]
Should be good to go @thisisamurray. Let me know if you run into any issues

**Comment by thisisamurray** [comment]
Everyone has `enableOnSite` removed.
